export type Permissoes = {
  BloquearParticipantePessoaFisica: boolean
  BloquearParticipantePessoaJuridica: boolean
  BloquearMotorista: boolean
  BloquearVeiculo: boolean
  BloquearTransportador: boolean
  BloquearTomador: boolean
  BloquearObservacaoEspecificaCliente: boolean
  CadastrarVeiculo: boolean
  CadastrarMotorista: boolean
  CadastrarParticipantePessoaJuridica: boolean
  CadastrarParticipantePessoaFisica: boolean
  CadastrarTransportador: boolean
  CadastrarTomador: boolean
  CadastrarObservacaoEspecificaCliente: boolean
  EditarVeiculo: boolean
  EditarMotorista: boolean
  EditarParticipantePessoaJuridica: boolean
  EditarParticipantePessoaFisica: boolean
  EditarTransportador: boolean
  EditarTomador: boolean
  EditarObservacaoEspecificaCliente: boolean
  CadastrarEditarObservacaoEspecificaCliente: boolean
  InserirObservacaoVeiculo: boolean
  InserirObservacaoMotorista: boolean
  InserirObservacaoParticipantePessoaJuridica: boolean
  InserirObservacaoParticipantePessoaFisica: boolean
  InserirObservacaoTransportador: boolean
  InserirObservacaoTomador: boolean
  InserirObservacaoObservacaoEspecificaCliente: boolean
  VisualizarObservacaoVeiculo: boolean
  VisualizarObservacaoMotorista: boolean
  VisualizarObservacaoParticipantePessoaJuridica: boolean
  VisualizarObservacaoParticipantePessoaFisica: boolean
  VisualizarObservacaoParticipanteTransportador: boolean
  VisualizarObservacaoTomador: boolean
  VisualizarObservacaoObservacaoEspecificaCliente: boolean
  ConsultarVeiculoAPISExternas: boolean
  ConsultarMotoristaAPISExternas: boolean
  ConsultarParticipantePessoaJuridicaAPISExternas: boolean
  ConsultarParticipantePessoaFisicaAPISExternas: boolean
  ConsultarParticipanteTransportadorAPISExternas: boolean
  ConsultarParticipanteTomadorAPISExternas: boolean
  HistoricoMotorista: boolean
  HistoricoVeiculo: boolean
  HistoricoTransportador: boolean
  HistoricoPessoaFisica: boolean
  HistoricoPessoaJuridica: boolean
  HistoricoVeiculoProprietario: boolean
  HistoricoVeiculoAgregador: boolean
  HistoricoCartaoTransportador: boolean
  HistoricoCartaoMotorista: boolean
  HistoricoTomador: boolean
  HistoricoObservacaoEspecificaCliente: boolean
  CartaoTransportadorReprocessar: boolean
  CartaoTransportadorCadastrar: boolean
  CartaoTransportadorEditar: boolean
  CartaoTransportadorCadastrarEditar: boolean
  CartaoTransportadorAtivarInativar: boolean
  CartaoTransportadorVisualizar: boolean
  CartaoMotoristaReprocessar: boolean
  CartaoMotoristaCadastrar: boolean
  CartaoMotoristaEditar: boolean
  CartaoMotoristaCadastrarEditar: boolean
  CartaoMotoristaAtivarInativar: boolean
  CartaoMotoristaVisualizar: boolean
  InserirGerenciamentoRiscoProprietario: boolean
  InserirGerenciamentoRiscoMotorista: boolean
  InserirGerenciamentoRiscoParticipantes: boolean
  CancelarGerenciamentoRiscoProprietario: boolean
  CancelarGerenciamentoRiscoMotorista: boolean
  CancelarGerenciamentoRiscoParticipantes: boolean
  VisualizarGerenciamentoRiscoProprietario: boolean
  VisualizarGerenciamentoRiscoMotorista: boolean
  VisualizarGerenciamentoRiscoParticipantes: boolean
  InserirObservacaoGerenciamentoRiscoParticipantes: boolean
  LiberarGerenciamentoRiscoParticipantes: boolean
  VisualizarHistoricoGerenciamentoRiscoParticipantes: boolean
  VisualizarHistoricoGerenciadoraDeRiscoConfiguracao: boolean
  VisualizarConfiguracaoGerenciadoraDeRisco: boolean
  InserirConfiguracaoGerenciadoraDeRisco: boolean
}
